"""Deduplication and re-auction detection.

Two problems that look identical and are not:

  1. The same asset published by several sources - BAANKNET, the bank's
     own PDF, an aggregator. Several records, one asset. Must collapse.

  2. The same asset auctioned again months later because the first
     auction failed. Two genuine events on one asset. Must NOT collapse,
     but must be linked - the price history is the most valuable thing
     the portal can show ("third attempt, reserve down 34%").

The discriminator is time and price direction: a match whose auction is
well in the future and whose reserve price has fallen is a new round, not
a duplicate.

Comparing every pair is not viable - 100,000 listings is five billion
comparisons. So candidates are generated by *blocking*: cheap keys that
similar records share, compared only within their block. A pair missed by
one key is usually caught by another.
"""

import logging
import re
from dataclasses import dataclass
from datetime import timedelta
from decimal import Decimal

from sqlalchemy import select
from sqlalchemy.orm import Session

from auction_portal.db.models import Listing

log = logging.getLogger(__name__)

#: Above this, merge without asking.
AUTO_MERGE = 0.85
#: Between this and AUTO_MERGE, flag for a human to look at.
REVIEW_FLOOR = 0.65

#: A re-auction is at least this far after the previous one.
REAUCTION_MIN_GAP = timedelta(days=25)

# Identity is judged only on properties of the *asset*, never on the price
# or the date.
#
# This matters more than it looks. A re-auction has, by definition, a later
# date and usually a lower price - so scoring those as differences makes the
# matcher worst at exactly the case it most needs to catch. Asking "is this
# the same thing?" and "is this the same event?" separately avoids that.
IDENTITY_WEIGHTS = {
    "address": 0.40,
    "area": 0.20,
    "locality": 0.15,
    "city": 0.15,
    "pincode": 0.10,
}

#: An exact reserve price match is corroborating evidence, never a penalty.
PRICE_MATCH_BONUS = 0.10

_NON_WORD = re.compile(r"[^a-z0-9 ]+")
_WHITESPACE = re.compile(r"\s+")

#: Words so common in Indian addresses that they carry no signal.
_STOPWORDS = frozenset(
    {
        "no",
        "plot",
        "flat",
        "house",
        "property",
        "near",
        "opp",
        "opposite",
        "road",
        "street",
        "nagar",
        "colony",
        "society",
        "village",
        "taluka",
        "district",
        "dist",
        "the",
        "at",
        "in",
        "and",
        "of",
        "part",
        "block",
        "ward",
        "survey",
        "old",
        "new",
    }
)


@dataclass(frozen=True, slots=True)
class MatchVerdict:
    relationship: str  # duplicate | reauction | review | distinct
    score: float
    reasons: tuple[str, ...] = ()


def normalise_address(text: str | None) -> str:
    """Reduce an address to comparable tokens."""
    if not text:
        return ""
    lowered = _NON_WORD.sub(" ", text.lower())
    tokens = [t for t in _WHITESPACE.split(lowered) if t and t not in _STOPWORDS]
    return " ".join(sorted(set(tokens)))


def blocking_keys(listing: Listing) -> set[str]:
    """Cheap keys that near-identical listings are likely to share.

    Several independent keys are used so that a pair missed by one is
    still caught by another.
    """
    keys: set[str] = set()

    if listing.asset_key:
        keys.add(f"asset:{listing.asset_key}")

    if listing.city and listing.reserve_price:
        bucket = int(listing.reserve_price / 100_000)  # nearest lakh
        keys.add(f"geo:{listing.state}:{listing.city}:{bucket}")

    if listing.pincode and listing.area_sqft:
        keys.add(f"pin:{listing.pincode}:{int(listing.area_sqft / 100)}")

    if listing.pincode and listing.reserve_price:
        keys.add(f"pinprice:{listing.pincode}:{int(listing.reserve_price / 100_000)}")

    tokens = normalise_address(listing.address).split()
    if len(tokens) >= 3:
        # A coarse fingerprint of the address wording.
        keys.add("addr:" + "|".join(tokens[:4]))

    return keys


def token_similarity(left: str, right: str) -> float:
    """Jaccard overlap of token sets - order-insensitive, which suits
    addresses written in inconsistent orders."""
    if not left or not right:
        return 0.0
    a, b = set(left.split()), set(right.split())
    if not a or not b:
        return 0.0
    return len(a & b) / len(a | b)


def similarity(left: Listing, right: Listing) -> tuple[float, list[str]]:
    """How likely two listings describe the same physical asset.

    Deliberately blind to reserve price and auction date, which change
    between rounds of the same asset. See IDENTITY_WEIGHTS.
    """
    reasons: list[str] = []

    # A shared source identifier settles it outright.
    if left.asset_key and right.asset_key and left.asset_key == right.asset_key:
        return 1.0, ["identical asset identifier"]

    scores: dict[str, float] = {}

    address_score = token_similarity(
        normalise_address(left.address), normalise_address(right.address)
    )
    if address_score:
        scores["address"] = address_score
        if address_score > 0.8:
            reasons.append("near-identical address")

    if left.area_sqft and right.area_sqft:
        bigger = max(left.area_sqft, right.area_sqft)
        gap = abs(left.area_sqft - right.area_sqft) / bigger
        scores["area"] = max(0.0, 1.0 - float(gap) * 5)

    if left.locality and right.locality:
        scores["locality"] = token_similarity(
            normalise_address(left.locality), normalise_address(right.locality)
        )

    if left.city and right.city:
        scores["city"] = 1.0 if left.city.lower() == right.city.lower() else 0.0

    if left.pincode and right.pincode:
        scores["pincode"] = 1.0 if left.pincode == right.pincode else 0.0

    if not scores:
        return 0.0, []

    total_weight = sum(IDENTITY_WEIGHTS[name] for name in scores)
    score = sum(value * IDENTITY_WEIGHTS[name] for name, value in scores.items()) / total_weight

    # Reserve prices are odd numbers like 3,37,55,000, so an exact match is
    # very unlikely to be coincidence. It can only raise confidence.
    if left.reserve_price and right.reserve_price and left.reserve_price == right.reserve_price:
        score = min(1.0, score + PRICE_MATCH_BONUS)
        reasons.append("identical reserve price")

    return score, reasons


def classify(earlier: Listing, later: Listing) -> MatchVerdict:
    """Decide the relationship between two listings.

    Two questions, asked in order:

      1. Is this the same asset?   -> identity similarity
      2. Is this the same event?   -> the gap between auction dates

    Same asset and same event means a duplicate to merge. Same asset, a
    later event means a new auction round to link and show the price
    history for.
    """
    score, reasons = similarity(earlier, later)

    if score < REVIEW_FLOOR:
        return MatchVerdict("distinct", score, tuple(reasons))

    if earlier.auction_start_at and later.auction_start_at:
        gap = later.auction_start_at - earlier.auction_start_at
        if gap >= REAUCTION_MIN_GAP:
            if (
                earlier.reserve_price
                and later.reserve_price
                and later.reserve_price < earlier.reserve_price
            ):
                discount = 1 - (later.reserve_price / earlier.reserve_price)
                return MatchVerdict(
                    "reauction",
                    score,
                    (*reasons, f"re-auction {discount:.0%} below previous reserve"),
                )
            return MatchVerdict("reauction", score, (*reasons, "later auction round"))

    if score >= AUTO_MERGE:
        return MatchVerdict("duplicate", score, tuple(reasons))
    return MatchVerdict("review", score, tuple(reasons))


class DuplicateFinder:
    """Finds duplicate and re-auction relationships across stored listings."""

    def __init__(self, session: Session):
        self._session = session

    def candidates(self, listing: Listing) -> list[Listing]:
        """Listings worth comparing against this one.

        Uses blocking so we never compare every pair. Restricted to the
        same asset class - a car cannot duplicate a warehouse.
        """
        keys = blocking_keys(listing)
        if not keys:
            return []

        pool = self._session.scalars(
            select(Listing).where(
                Listing.id != listing.id,
                Listing.asset_class == listing.asset_class,
            )
        )
        return [other for other in pool if keys & blocking_keys(other)]

    def find_for(self, listing: Listing) -> list[tuple[Listing, MatchVerdict]]:
        matches = []
        for other in self.candidates(listing):
            earlier, later = _in_time_order(listing, other)
            verdict = classify(earlier, later)
            if verdict.relationship != "distinct":
                matches.append((other, verdict))
        return sorted(matches, key=lambda pair: pair[1].score, reverse=True)

    def scan(self, limit: int | None = None) -> dict[str, int]:
        """Sweep all listings and report what was found.

        Reports rather than mutates: merging is destructive and a wrong
        merge is much harder to notice than a missed one, so the counts
        are reviewed before any automatic merging is switched on.
        """
        stmt = select(Listing).order_by(Listing.id)
        if limit:
            stmt = stmt.limit(limit)
        listings = list(self._session.scalars(stmt))

        tally = {"duplicate": 0, "reauction": 0, "review": 0, "compared": 0}
        seen: set[tuple[int, int]] = set()

        for listing in listings:
            for other, verdict in self.find_for(listing):
                pair = (min(listing.id, other.id), max(listing.id, other.id))
                if pair in seen:
                    continue
                seen.add(pair)
                tally["compared"] += 1
                tally[verdict.relationship] += 1
                log.info(
                    "%s (%.2f): %s <-> %s  %s",
                    verdict.relationship,
                    verdict.score,
                    listing.id,
                    other.id,
                    "; ".join(verdict.reasons),
                )

        return tally


def _in_time_order(left: Listing, right: Listing) -> tuple[Listing, Listing]:
    if left.auction_start_at and right.auction_start_at:
        return (left, right) if left.auction_start_at <= right.auction_start_at else (right, left)
    return (left, right) if left.id <= right.id else (right, left)


def price_change(earlier: Decimal | None, later: Decimal | None) -> Decimal | None:
    """Fractional change between two reserve prices; negative is a cut."""
    if not earlier or not later or earlier == 0:
        return None
    return ((later - earlier) / earlier).quantize(Decimal("0.0001"))
