"""canonical content hash

Revision ID: 0035c50fc4a9
Revises: b1a2d45fcff8
Create Date: 2026-09-30 21:25:39.018366

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0035c50fc4a9"
down_revision: Union[str, Sequence[str], None] = "b1a2d45fcff8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("url_state", sa.Column("canonical_sha256", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("url_state", "canonical_sha256")
    # ### end Alembic commands ###
