"""listing area fields

Revision ID: 1b15da44f449
Revises: ac01cc5358ba
Create Date: 2026-09-26 23:21:38.599522

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1b15da44f449"
down_revision: Union[str, Sequence[str], None] = "ac01cc5358ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "listings", sa.Column("area_value", sa.Numeric(precision=14, scale=2), nullable=True)
    )
    op.add_column("listings", sa.Column("area_unit", sa.String(length=24), nullable=True))
    op.add_column(
        "listings", sa.Column("area_sqft", sa.Numeric(precision=14, scale=2), nullable=True)
    )
    op.create_index(op.f("ix_listings_area_sqft"), "listings", ["area_sqft"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_listings_area_sqft"), table_name="listings")
    op.drop_column("listings", "area_sqft")
    op.drop_column("listings", "area_unit")
    op.drop_column("listings", "area_value")
    # ### end Alembic commands ###
