"""source_documents and url_state

Revision ID: 776b396f42d9
Revises:
Create Date: 2026-09-26 22:36:54.580635

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "776b396f42d9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_documents",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("mime_type", sa.String(length=128), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("etag", sa.String(length=256), nullable=True),
        sa.Column("last_modified", sa.String(length=128), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_url", "content_sha256", name="uq_source_doc_url_hash"),
    )
    op.create_index("ix_source_doc_sha256", "source_documents", ["content_sha256"], unique=False)
    op.create_index(
        "ix_source_doc_source_fetched",
        "source_documents",
        ["source_id", "fetched_at"],
        unique=False,
    )
    op.create_table(
        "url_state",
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("etag", sa.String(length=256), nullable=True),
        sa.Column("last_modified", sa.String(length=128), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fetch_count", sa.Integer(), nullable=False),
        sa.Column("unchanged_streak", sa.Integer(), nullable=False),
        sa.Column("current_document_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["current_document_id"], ["source_documents.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("url"),
    )
    op.create_index("ix_url_state_source", "url_state", ["source_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_url_state_source", table_name="url_state")
    op.drop_table("url_state")
    op.drop_index("ix_source_doc_source_fetched", table_name="source_documents")
    op.drop_index("ix_source_doc_sha256", table_name="source_documents")
    op.drop_table("source_documents")
    # ### end Alembic commands ###
