"""listings and listing_revisions

Revision ID: ac01cc5358ba
Revises: 776b396f42d9
Create Date: 2026-09-26 23:15:43.628577

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ac01cc5358ba"
down_revision: Union[str, Sequence[str], None] = "776b396f42d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "listings",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("asset_key", sa.String(length=128), nullable=True),
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column("source_document_id", sa.BigInteger(), nullable=True),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column("asset_class", sa.String(length=32), nullable=False),
        sa.Column("asset_type", sa.String(length=64), nullable=True),
        sa.Column("asset_subtype", sa.String(length=128), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("locality", sa.Text(), nullable=True),
        sa.Column("city", sa.String(length=128), nullable=True),
        sa.Column("district", sa.String(length=128), nullable=True),
        sa.Column("state", sa.String(length=128), nullable=True),
        sa.Column("pincode", sa.String(length=10), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("reserve_price", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("emd_amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("bid_increment", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("outstanding_dues", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("auction_start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("auction_end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("emd_deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("inspection_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("inspection_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("bank_name", sa.String(length=160), nullable=True),
        sa.Column("branch_name", sa.String(length=200), nullable=True),
        sa.Column("possession_type", sa.String(length=16), nullable=True),
        sa.Column("symbolic_possession_date", sa.Date(), nullable=True),
        sa.Column("physical_possession_date", sa.Date(), nullable=True),
        sa.Column("npa_date", sa.Date(), nullable=True),
        sa.Column("legal_basis", sa.String(length=32), nullable=True),
        sa.Column("authorised_officer_name", sa.String(length=200), nullable=True),
        sa.Column("authorised_officer_phone", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("quality_flags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_verified_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_document_id"], ["source_documents.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "external_id", name="uq_listing_source_external"),
    )
    op.create_index("ix_listing_bank", "listings", ["bank_name"], unique=False)
    op.create_index("ix_listing_geo", "listings", ["state", "city", "asset_type"], unique=False)
    op.create_index(
        "ix_listing_live",
        "listings",
        ["status", "auction_start_at"],
        unique=False,
        postgresql_where=sa.text("status IN ('upcoming', 'live')"),
    )
    op.create_index(op.f("ix_listings_asset_key"), "listings", ["asset_key"], unique=False)
    op.create_index(op.f("ix_listings_bank_name"), "listings", ["bank_name"], unique=False)
    op.create_index(op.f("ix_listings_city"), "listings", ["city"], unique=False)
    op.create_index(op.f("ix_listings_pincode"), "listings", ["pincode"], unique=False)
    op.create_index(op.f("ix_listings_reserve_price"), "listings", ["reserve_price"], unique=False)
    op.create_index(op.f("ix_listings_state"), "listings", ["state"], unique=False)
    op.create_table(
        "listing_revisions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("listing_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("field_name", sa.String(length=64), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("source_document_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(["listing_id"], ["listings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_document_id"], ["source_documents.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_revision_listing", "listing_revisions", ["listing_id", "changed_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_revision_listing", table_name="listing_revisions")
    op.drop_table("listing_revisions")
    op.drop_index(op.f("ix_listings_state"), table_name="listings")
    op.drop_index(op.f("ix_listings_reserve_price"), table_name="listings")
    op.drop_index(op.f("ix_listings_pincode"), table_name="listings")
    op.drop_index(op.f("ix_listings_city"), table_name="listings")
    op.drop_index(op.f("ix_listings_bank_name"), table_name="listings")
    op.drop_index(op.f("ix_listings_asset_key"), table_name="listings")
    op.drop_index(
        "ix_listing_live",
        table_name="listings",
        postgresql_where=sa.text("status IN ('upcoming', 'live')"),
    )
    op.drop_index("ix_listing_geo", table_name="listings")
    op.drop_index("ix_listing_bank", table_name="listings")
    op.drop_table("listings")
    # ### end Alembic commands ###
