"""source health listings seen

Revision ID: b1a2d45fcff8
Revises: 800d43af2fb7
Create Date: 2026-09-27 00:48:04.520951

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b1a2d45fcff8"
down_revision: Union[str, Sequence[str], None] = "800d43af2fb7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows; NOT NULL cannot be added to a
    # populated table without one. Dropped afterwards so the application
    # remains the only thing that sets the value.
    op.add_column(
        "source_health",
        sa.Column("listings_seen", sa.Integer(), nullable=False, server_default="0"),
    )
    op.alter_column("source_health", "listings_seen", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("source_health", "listings_seen")
    # ### end Alembic commands ###
