"""listing full text search

Revision ID: e5a0dcfd8ee2
Revises: 1b15da44f449
Create Date: 2026-09-27 00:18:53.101608

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e5a0dcfd8ee2"
down_revision: Union[str, Sequence[str], None] = "1b15da44f449"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "listings",
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "setweight(to_tsvector('simple', coalesce(title, '')), 'A') || setweight(to_tsvector('simple', coalesce(city, '')), 'B') || setweight(to_tsvector('simple', coalesce(locality, '')), 'B') || setweight(to_tsvector('simple', coalesce(state, '')), 'B') || setweight(to_tsvector('simple', coalesce(bank_name, '')), 'C') || setweight(to_tsvector('simple', coalesce(address, '')), 'D')",
                persisted=True,
            ),
            nullable=True,
        ),
    )
    op.create_index(
        "ix_listing_search", "listings", ["search_vector"], unique=False, postgresql_using="gin"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_listing_search", table_name="listings", postgresql_using="gin")
    op.drop_column("listings", "search_vector")
    # ### end Alembic commands ###
